# Site Settings
title: "MK4PROMO"
description: "مرحباً بك في موقع روابط الإحالة الخاصة بي. هنا ستجد أفضل العروض والمنتجات."
permalink: ':title/'
baseurl: ""
url: "https://mk4travelink.github.io"
site-twitter: 

# Author Settings
author: 
author-img: Logo.png?v=4
about-author: "Between flights and footpaths, for lovers of maps, mountains, and mornings in strange cities — a travel diary for the curious soul.
"
social-twitter: 
social-facebook: 
social-github: mk4promo
social-linkedin: 
social-email: 

# Disqus
discus-identifier:

# Tracker
analytics: 

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginator
  - jemoji

paginate: 
paginate_path: 

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
