# Site Settings
title: "MK4PROMO"
description: "مرحباً بك في موقع روابط الإحالة الخاصة بي. هنا ستجد أفضل العروض والمنتجات."
permalink: ':title/'
baseurl: ""
url: "https://mk4promo.github.io"
site-twitter: 

# Author Settings
author: mk4promo
author-img: assets/img/logo.png
about-author: "Between flights and footpaths, for lovers of maps, mountains, and mornings in strange cities — a travel diary for the curious soul.
"
social-twitter: 
social-facebook: 
social-github: mk4promo
social-linkedin: 
social-email: 

# Disqus
discus-identifier: mr-brown

# Tracker
analytics: 

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginator
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
